### ISSUE TITLE
list_dir fails on empty directory

### ISSUE THREAD

**Issue by jric** [tommybutler/file-util#1]
I create an empty directory:  `mkdir /Users/jric/tmp/foo`, then ran the following script:

```
use File::Util;
my ($f) = File::Util->new(
             {
                onfail => sub {
                   my ( $err, $stack ) = @_;

                   die($err . "; $stack");
                }
             }
          );
my $outdir = '/Users/jric/tmp/foo';
print $f->list_dir($outdir => {dirs_only => 1, no_fsdots => 1,
                           dirs_match => qr/^lookinforsomething$/});
```

The result confused me:

> Can't use an undefined value as an ARRAY reference at 
> /opt/local/lib/perl5/site_perl/5.12.4/File/Util.pm line 454.

If I `use diagnostics`, I get more confused:

> ```
> (F) A value used as either a hard reference or a symbolic reference must
> be a defined value.  This helps to delurk some insidious errors.
> ```

Looking at the code, I think this can all be avoided with this patch to `Util.pm`:

> ```
> 118c118,119
> <    my ( @dir_contents, $subdirs, $files );
> ---
> >    my ( @dir_contents );
> >    my ( $subdirs, $files ) = ( [], [] );
> ```

**Comment by tommybutler** [comment]
Thank you for this bug report Joshua. I'll work on it this weekend. Thanks again!

– – Tommy

Joshua Richardson notifications@github.com wrote:

> I create an empty directory:  `mkdir /Users/jric/tmp/foo`, then ran the
> following script:
> 
>    use File::Util;
>    my ($f) = File::Util->new(
>                 {
>                    onfail => sub {
>                       my ( $err, $stack ) = @_;
> 
> ```
>                   die($err . "; $stack");
>                }
>             }
>          );
> ```
> 
>    my $outdir = '/Users/jric/tmp/foo';
>    print $f->list_dir($outdir => {dirs_only => 1, no_fsdots => 1,
>                              dirs_match => qr/^lookinforsomething$/});
> 
> The result confused me:
> 
> > Can't use an undefined value as an ARRAY reference at 
> > /opt/local/lib/perl5/site_perl/5.12.4/File/Util.pm line 454.
> 
> If I `use diagnostics`, I get more confused:
> 
> > ```
> > (F) A value used as either a hard reference or a symbolic
> > ```
> > 
> > reference must
> >     be a defined value.  This helps to delurk some insidious errors.
> 
> Looking at the code, I think this can all be avoided with this patch to
> `Util.pm`:
> 
> > 118c118,119
> > 
> > ## <    my ( @dir_contents, $subdirs, $files );
> > 
> > >    my ( @dir_contents );
> > >    my ( $subdirs, $files ) = ( [], [] );
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tommybutler/file-util/issues/1

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by renatocron** [comment]
Hello @tommybutler, this looks fixed. I just run some tests and it looks fine (do not die)
